name: demo runner

on: push

jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - run: echo $HOSTNAME
      - run: echo 'this is demo runner'
